baseURL: "https://usrbin.top/"
languageCode: "en-us"
title: "Laura Martin"
theme: "minimal"
pluralizeListTitles: false

params:
  author: "Laura Martin"
  description: "Operations Engineer"
  githubUsername: "surminus"
  accent: "black"
  showBorder: true
  backgroundColor: "white"
  font: "Arima" # should match the name on Google Fonts!
  copyright: "&copy; All rights reserved. Built with [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal), deployed and hosted by [Netlify](https://www.netlify.com/)"

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

menu:
  main:
  - url: "/"
    name: "Home"
    weight: 1

  - url: "/blog/"
    name: "Blog"
    weight: 2

  - url: "/about/"
    name: "About"
    weight: 3

  - url: "/cv/"
    name: "CV"
    weight: 4

  - url: "/gpg/"
    name: "GPG"
    weight: 4

  icon:
  - url: "mailto:work@surminus.com"
    name: "envelope-o"
    weight: 1

  - url: "https://github.com/surminus/"
    name: "github"
    weight: 3

  - url: "https://www.linkedin.com/in/laura-martin-9571a921/"
    name: "linkedin"
    weight: 5
