baseURL: "https://usrbin.top/"
languageCode: "en-us"
title: "Laura Martin"
theme: "minimal"

params:
  author: "Laura Martin"
  description: "Operations Engineer"
  githubUsername: "surminus"
  accent: "black"
  showBorder: true
  backgroundColor: "white"
  font: "Abel" # should match the name on Google Fonts!

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

menu:
  icon:
  - url: "mailto:surminus@gmail.com"
    name: "envelope-o"
    weight: 1

  - url: "https://surminus.github.io"
    name: "book"
    weight: 2

  - url: "https://github.com/surminus/"
    name: "github"
    weight: 3

  - url: "https://twitter.com/surminus/"
    name: "twitter"
    weight: 4

  - url: "https://www.linkedin.com/in/laura-martin-9571a921/"
    name: "linkedin"
    weight: 5
